# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

#before_install:
#  - sudo apt-get install liblapack-dev gfortran

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install:
#  - travis_wait pip install -r requirements.txt


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing
  # on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas PyYAML
  - pip install pytest
  - pip install popgen

# command to run tests, e.g. python setup.py test
script:
  - py.test
